### ISSUE TITLE
Deploy server waffle chart issue

### ISSUE THREAD

**Issue by YoungjunNa** [shinykorea/corona-sickbed#14]
@jinseob2kim 

진섭님. 서버에 배포하시느라 고생하셨습니다! deploy version 서버에 와플차트가 보이질 않는데요.
패키지 의존성 문제인 것 같습니다. Dev version 을 사용해야 할 것 같습니다!

`devtools::install_github("hrbrmstr/waffle")`

**Comment by jinseob2kim** [comment]
업데이트 했습니다. http://app.zarathu.com/corona/corona-sickbed/
