### ISSUE TITLE
생활치료센터 확장성

### ISSUE THREAD

**Issue by YoungjunNa** [shinykorea/corona-sickbed#16]
장기적으로 [생활치료센터](http://ncov.mohw.go.kr/tcmBoardView.do?brdId=3&brdGubun=31&dataGubun=&ncvContSeq=756&contSeq=756&board_id=311&gubun=BDC) 확장성을 고려할 필요가 있을 것으로 보입니다.

**Comment by jinseob2kim** [comment]
그러네요. 현황, 중증도 평가 모두 해당될것 같습니다
