### ISSUE TITLE
지도 Pie 그래프 클릭시 병원명 추가

### ISSUE THREAD

**Issue by jinseob2kim** [shinykorea/corona-sickbed#22]
현재는 Pie 그래프 클릭 시, **사용/가용병상** 만 나오는데, 그 위에 병원명도 표시해주면 좋아 보입니다. 지도위치만으로는 병원명 파악 어려워 보입니다.

**Comment by YoungjunNa** [comment]
추가 하였습니다. 고맙습니다!
