### ISSUE TITLE
폰트 설정법

### ISSUE THREAD

**Issue by jhk0530** [shinykorea/corona-sickbed#23]
1. `www` 디렉토리에 `ttf`, `css` 파일 첨부
```
app.R
/www
    - Title_Bold.ttf ...
    - includefont.css
```

2. UI 에서 `body` 부분에 `includeCSS` 로 `css` 파일 로드 

```R
fluidPage(
    tags$head(includeCSS("www/includefont.css")),
)
```
3. `body` 에 `font-familly` 속성 설정 
(필요에 따라 전체에 설정하지 말고 부분별로 class 줘서 bold, light, medium 설정 해도 좋을 듯)

```R
tags$head(tags$style(type = "text/css", "*{font-family:GGTitle_L}")),
```

![image](https://user-images.githubusercontent.com/6457691/76731160-1c924e00-67a0-11ea-80d1-311f9766af28.png)

**Comment by YoungjunNa** [comment]
고맙습니다^^ 덕분에 대시보드가 한결 풍성해 졌네요
