### ISSUE TITLE
색상 조절

### ISSUE THREAD

**Issue by jhk0530** [shinykorea/corona-sickbed#24]
![image](https://user-images.githubusercontent.com/6457691/76824003-23c96280-6859-11ea-8d48-147a6f44ce66.png)

`사용중인` 내용의 색상을 회색에서

주황색이나, 노란색

- ![#f6a21c](https://placehold.it/15/f6a21c/000000?text=+) `#f6a21c`
- ![#ffed82](https://placehold.it/15/ffed82/000000?text=+) `#ffed82`

으로 바꿔도 좋을것 같습니다.

---

회색이 지정 되었다고 들었는데요, 

아쉬운대로, border 에 color - ![#000000](https://placehold.it/15/000000/000000?text=+) `#000000` 속성을 줘서 구분 지어도 좋을것 같습니다.

**Comment by YoungjunNa** [comment]
의견 감사합니다^^ 
일단 이 부분은 end user와 직접 커뮤니케이션 하면서 색을 지정한 부분이라 제안은 드려 보도록 하겠습니다!
