### ISSUE TITLE
Dropbox 접근허가팝업 문제.

### ISSUE THREAD

**Issue by jinseob2kim** [shinykorea/corona-sickbed#25]
저만 그런진 모르겠는데, 서버환경에서 `drop_acc(dtoken = token)` 을 실행해서 접근을 승인할 수가 없습니다.
![Screenshot from 2020-03-18 10-41-15](https://user-images.githubusercontent.com/33089958/76916818-0520a580-6905-11ea-983b-dcd6d6037690.png)
![Screenshot from 2020-03-18 10-41-18](https://user-images.githubusercontent.com/33089958/76916822-081b9600-6905-11ea-848f-f506338025c4.png)

해결은 아래와 같이  `drop_acc(dtoken = token)`  는 지우고, Dropbox 함수 관련 실행할 때 마다 토큰을 지정해주었습니다.

```r
library(rdrop2)
token <- readRDS("token.rds")
#drop_acc(dtoken = token)

file <- drop_dir("corona19", dtoken = token) %>%
  select(name, client_modified) %>%
  arrange(desc(client_modified))

file_name <- file %>%
  pull(name) %>%
  .[1]

file_date <- file %>%
  pull(client_modified) %>%
  .[1] %>%
  lubridate::ymd_hms()

paste0("corona19/", file_name) %>%
  drop_download(local_path = "data", overwrite = TRUE, dtoken = token)
```

**Comment by YoungjunNa** [comment]
고맙습니다 진섭님 잘 적용하였습니다 ^^
