### ISSUE TITLE
음압병동현황/메인화면/사용률 글씨색상

### ISSUE THREAD

**Issue by PyeongsaengCoding** [shinykorea/corona-sickbed#5]
빨간바탕에 검은글씨보단 하얀 글씨가 보기 좋을거같아요~
![캡처](https://user-images.githubusercontent.com/24456683/75636512-c206d700-5c62-11ea-907c-75c94c2df650.PNG)

**Comment by skysign** [comment]
저도 비슷한 생각을 했는대, issue로 올려주셨네요.

**Comment by YoungjunNa** [comment]
반영하였습니다^^ 디테일한 의견 감사합니다.

**Comment by skysign** [comment]
제가 한번 고처볼까 하고, 코드 보고 있었는대, 벌써고치셨네요 ^^a

**Comment by skysign** [comment]
이런 자잘한 수정은 초보자들 해보라고 기회를 좀 주셔도 좋을 것 같습니다. ^^a

**Comment by YoungjunNa** [comment]
넵넵! ㅎㅎ 감사합니다..!! 풀리퀘는 환영입니다!
