### ISSUE TITLE
지도에 반영 할 수 있을 것으로 생각되는 정보들

### ISSUE THREAD

**Issue by JaehyeongCho** [shinykorea/corona-sickbed#7]
* 시/군/구/도 단위로 분리하여 polygons 형태로 표현
  - 클릭시 확진자, 증가된 환자 수, 완치된 환자 수 등
* 확진자 거주지를 point로 표현
  - 클릭시 확진된 날짜, 이전 감염자 접촉일자 등
* 음압병실이 설치된 병원의 위치를 point로 표현
  - 병실 현황, 병원 정보 등

**Comment by YoungjunNa** [comment]
의견 정말 고맙습니다!

일단 제가 듣기로는 
1. 경기도에서 관리하는 병동 현황을 관리하는게 목표이고
2. 경기도측에서 데이터 입력할 것을 최소화 하면 좋을 듯 하여
3. 거주지라던지 감염자 접촉일 등 역학조사(?) 관련된 내용은 본 shiny app 보다는 따로 확장된 앱에서 적용하면 좋을 것 같습니다! 🙂
4. polygons 형태로 표현/음압병실 위치 point 표현은 한번 시도해 보겠습니다. 아니면 풀 리퀘로 주세요! 고맙스빈다!

@jinseob2kim 추가의견 부탁드려요!

**Comment by jinseob2kim** [comment]
시/군/구 단위보다는, **병원 위치**와 **병상 현황**이 중요합니다.
- 지도 보는 것만으로도(클릭 없이) 병원 위치와  중환자실/일반병실 음압병상 현황을 볼 수 있어야 합니다.
- 클릭하면 A/B/C/D/E 등급 별 등 세부 자료 확인 
- ploygon 적용하면, 병원위치와 병상현황이 더 잘 보일 수 있을것 같습니다.

확진자 거주지는 지도에 보여줄 필요 없어 보입니다. 
- 경기도팀에서 요청올 때 고려하면 좋겠습니다.

**Comment by takos1026** [comment]
지도상에 데이터 표현방식으로 상열님께서 한번 소개해주셨던 leaflet.minichart 패키지 검토 부탁드립니다. 
https://github.com/rte-antares-rpackage/leaflet.minicharts/blob/master/README.md

**Comment by takos1026** [comment]
leaflet 타일 옵션으로 addProviderTiles("CartoDB.VoyagerLabelsUnder") 주시면 포탈에서 제공하는 맵과 유사한 느낌으로 표현 가능합니다. 중요도는 낮습니다.

**Comment by YoungjunNa** [comment]
좋은데요? 현재 이렇게 쓰고 있는데, 어떻게 코드를 바꿔야 할까요?🤔
```
    leaflet() %>%
      addTiles() %>%
      addMinicharts(
        join()$long, join()$lat,
        type = "pie",
        chartdata = join()[, c("사용", "여유")],
        colorPalette = c("#fe346e", "#cccccc")
      ) 
```

**Comment by takos1026** [comment]
수정했습니다.
```
    leaflet() %>%
      addProviderTiles("CartoDB.VoyagerLabelsUnder")  %>%
      addMinicharts(
        join()$long, join()$lat,
        type = "pie",
        chartdata = join()[, c("사용", "여유")],
        colorPalette = c("#fe346e", "#cccccc")
      ) 
```
아래코드로 적용 가능한 타일목록을 볼 수 있는데 우리나라 영역이 안나오는 옵션들도 있습니다. CartoDB 시리즈 추천 드려요
```
names(providers)
```

**Comment by YoungjunNa** [comment]
고맙습니다 :)
제 version의 leaflet에는 "CartoDB.VoyagerLabelsUnder" 가 없네요?
names(providers) 보고 잘 골라보겠습니다 ㅎㅎ
